
services:

  web:
    image: httpd:2.4
    container_name: vuln_apache
    ports:
      - "8082:80"
    volumes:
      - ./www:/usr/local/apache2/htdocs:rw
      - ./apache_conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    restart: unless-stopped
   

  ftp:
    image: fauria/vsftpd:latest
    container_name: vuln_ftp
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=testuser
      - FTP_PASS=testpass
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - ANONYMOUS_ENABLE=YES 
    restart: unless-stopped

 
  ssh:
    image: linuxserver/openssh-server:latest
    container_name: vuln_ssh
    ports:
      - "2222:22"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - USER_NAME=testssh
      - USER_PASSWORD=sshpass 
    restart: unless-stopped

  db:
    image: mysql:5.7 
    container_name: vuln_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretrootpass
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass 
    restart: unless-stopped


